[mypy]
python_version = 3.11
strict = true
exclude = tests/fixtures/

[mypy-google.*]
ignore_missing_imports = true

[mypy-lancedb.*]
ignore_missing_imports = true

[mypy-tree_sitter_languages.*]
ignore_missing_imports = true